version: '3'

services:
  algod:
    container_name: "algorand-sandbox-algod"
    build:
      context: .
      dockerfile: ./images/algod/Dockerfile
      args:
        CHANNEL: "${ALGOD_CHANNEL}"
        URL: "${ALGOD_URL}"
        BRANCH: "${ALGOD_BRANCH}"
        SHA: "${ALGOD_SHA}"
        BOOTSTRAP_URL: "${NETWORK_BOOTSTRAP_URL}"
        GENESIS_FILE: "${NETWORK_GENESIS_FILE}"
        TEMPLATE: "${NETWORK_TEMPLATE:-/tmp/images/algod/template.json}"
        TOKEN: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        ALGOD_PORT: "4001"
        KMD_PORT: "4002"
    ports:
      - 4001:4001
      - 4002:4002

  indexer:
    container_name: "algorand-sandbox-indexer"
    build:
      context: .
      dockerfile: ./images/indexer/Dockerfile
      args:
        URL: "${INDEXER_URL}"
        BRANCH: "${INDEXER_BRANCH}"
        SHA: "${INDEXER_SHA}"
    ports:
      - 8980:8980
    restart: unless-stopped
    environment:
      DISABLED: "${INDEXER_DISABLED}"
      PORT: "8980"
      SNAPSHOT: ""
      CONNECTION_STRING: "host=indexer-db port=5432 user=algorand password=algorand dbname=indexer_db sslmode=disable"
      ALGOD_ADDR: "algod:4001"
      ALGOD_TOKEN: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    depends_on:
      - indexer-db
      - algod

  indexer-db:
    image: "postgres:13-alpine"
    container_name: "algorand-sandbox-postgres"
    ports:
      - 5433:5432
    user: postgres
    environment:
      POSTGRES_USER: algorand
      POSTGRES_PASSWORD: algorand
      POSTGRES_DB: indexer_db

  tiquet-privnet:
    container_name: "tiquet-privnet"
    build:
      context: .
      dockerfile: ./images/tiquet/Dockerfile
    environment:
      ALGOD_ADDR: "http://localhost:4001"
      ALGOD_TOKEN: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
      APP_FPATH: "/root/tiquet/teal/tiquet_app.teal"
      CLEAR_FPATH: "/root/tiquet/teal/clear.teal"
      ESCROW_FPATH: "/root/tiquet/teal/escrow.teal"
      SUCCESS_TEAL_FPATH: "/root/tiquet/teal/success.teal"
      MNEMONICS_FILE: "/tmp/config/mnemonics_privnet.txt"
      NETWORK: "privnet"
    volumes:
      - type: bind
        source: ./tiquet
        target: /root/tiquet
    depends_on:
      - algod

  tiquet-testnet:
    container_name: "tiquet-testnet"
    build:
      context: .
      dockerfile: ./images/tiquet/Dockerfile
    environment:
      ALGOD_ADDR: "https://testnet-algorand.api.purestake.io/ps2"
      ALGOD_TOKEN: "LGlsGlaSiY37Y3xKQly071AsDwS6PeP73mAaFJLF"
      APP_FPATH: "/root/tiquet/teal/tiquet_app.teal"
      CLEAR_FPATH: "/root/tiquet/teal/clear.teal"
      ESCROW_FPATH: "/root/tiquet/teal/escrow.teal"
      SUCCESS_TEAL_FPATH: "/root/tiquet/teal/success.teal"
      MNEMONICS_FILE: "/tmp/config/mnemonics_testnet.txt"
      NETWORK: "testnet"
    volumes:
      - type: bind
        source: ./tiquet
        target: /root/tiquet
    depends_on:
      - algod
