# TODO(hv): Make final
TIQUET_PROCESSING_FEE_NUMERATOR_GLOBAL_VAR_NAME = "PROCESSING_FEE_NUMERATOR"
TIQUET_PROCESSING_FEE_DENOMINATOR_GLOBAL_VAR_NAME = "PROCESSING_FEE_DENOMINATOR"
TIQUET_PRICE_GLOBAL_VAR_NAME = "PRICE"
TIQUET_ISSUER_ROYALTY_NUMERATOR_GLOBAL_VAR_NAME = "ROYALTY_NUMERATOR"
TIQUET_ISSUER_ROYALTY_DENOMINATOR_GLOBAL_VAR_NAME = "ROYALTY_DENOMINATOR"
TIQUET_FOR_SALE_FLAG_GLOBAL_VAR_NAME = "FOR_SALE"
TIQUET_ESCROW_ADDRESS_GLOBAL_VAR_NAME = "ESCROW_ADDRESS"
